### ISSUE TITLE
Sem issues?

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/robotsgame#1]
?

**Comment by wagner-lucas** [comment]
Professor, é que na medida que os problemas iao aparecendo, a gente  ficava na faculdade e resolvia juntos. Por isso não temos issues.

**Comment by drbeco** [comment]
Infelizmente essa justificativa não contribui em. Aqui não é local para justificativas. Estou apontando o problema e vocês devem resolver melhorando a atividade, registrando melhor a contribuição, etc. Façam melhor uso da ferramenta.
