### ISSUE TITLE
Adicionar AUTHORS

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/robotsgame#4]
Falta arquivo com nomes de autores

**Comment by drbeco** [comment]
No ramo master!

**Comment by alessonrenato** [comment]
Arquivo inserido professor. Coloquei também a versão b do exercício que criei após o prazo para testar os caracteres especiais de tabela caso o Sr. queira mudar as configurações do hydra para que eles funcionem.

**Comment by alessonrenato** [comment]
Acabei de testar a versão b no servidor e ele está funcionando normalmente.
