### ISSUE TITLE
[bug] casa adjacentes

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/robotsgame#7]
Alesson estava jogando o robots, procurando algum bug e percebi que quando estou em adjacente com o robô ele ao invés de atacar o jogador(matar) ele foge do jogador, fazendo a ação contraria.

**Comment by alessonrenato** [comment]
também percebi isso, vou tentar olhar com o gdb.

**Comment by alessonrenato** [comment]
eu debuguei com o gdb e vi que o programa procura o humano na função computador joga mas entrega a coordenada iH com um valor errado,  1 número acima do correto. talvez passando o if com o break pra depois do segundo for (jH) o problema se resolva.

**Comment by wagner-lucas** [comment]
Eu corrigi o bug, apenas adicionei uma linha de código decrementando a variável (iH), agora ela está retornando o valor certo e o robô esta fazendo a ação correta.

**Comment by alessonrenato** [comment]
coloca o

```
if(achouH==1)
            break;
```
depois do
```
for(jH=0;jH<MAXTAB;jH++)
            if(d.tab[iH][jH] == 2)
            {
                achouH = 1;
                break;
            }
```
e apaga o decremento.

desse jeito fica uma solução mais limpa logicamente.

**Comment by drbeco** [comment]
Desse jeito, Alesson, **FICA UMA SOLUÇÃO!!**. Do outro jeito, USAR DECREMENTO?????, isso não se faz! Que isso, Wagner!!! Socorro! Como que você **"resolve"** o problema de um valor errado decrementando e não procurando a causa??! Isso não se faz; não pode fazer "quebra-galhos" assim!! E se o erro fosse dois a mais? Iria fazer `iH--; iH--;`? E se fosse o dobro a mais? Iria dividir por dois? Ah, que isso, Wagner. Cuidado, não quero ler esse tipo de erro novamente, ou você vai comprometer seriamente minha avaliação sobre seu processo de raciocínio de programação. Esteja avisado!

**Comment by wagner-lucas** [comment]
Entendi alesson, testei o que você falou e resolveu o problema. É que quando estava olhando mais cedo e você falou do valor que estava retornando errado, eu fui direto no jeito mais fácil, sem prestar  atenção na estrutura logica do executamento do código. 
Certo professor, quando eu estiver tentando resolver um problema não vou mais usar essas idéias quebradas.
